name: build adoc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor

    steps:
      - uses: actions/checkout@v3

      - name: Build HTML
        run: asciidoctor -v -D docs -a data-uri --backend=html5 -o hackathon.html index.adoc

      #- name: Build PDF
      #  run: asciidoctor-pdf -v -D docs -o hackathon.pdf index.adoc

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/*
