name: build slides for gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor

    steps:
      - uses: actions/checkout@v3

      - name: Setup reveal.js
        run: |
          git clone -b 4.1.2 --depth 1 https://github.com/hakimel/reveal.js.git
          mkdir -p slides/reveal.js
          mv reveal.js/dist slides/reveal.js/
          mv reveal.js/plugin slides/reveal.js/

      - name: Build slides
        run: asciidoctor-revealjs -v -D slides index.adoc

      - name: Copy slide resources
        run: |
          mv -v images static/slides
          mv -v css static/slides

      - name: Push generated files to branch 'gh-pages'
        run: |
          mkdir -p static/slides
          mv -v slides/* static/slides
          cd static/slides
          git init -b main
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[release] Publish on GitHub Pages"
          git push --force origin main:gh-pages
        if: ${{ success() }}
